import Script from "next/script";

export const metadata = {
  title: "More Than Chat API Test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Script src="/library/p5llm.js" strategy="beforeInteractive"></Script>
        <Script src="/library/textBox.js" strategy="beforeInteractive"></Script>
        {children}
      </body>
    </html>
  );
}
